### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Kothata** [Nimbleguy/The-Void#5]
Grammar Nazi here, sorry lol. Great mod, but it's been bugging me for a while how you've used the word inhabitable. Inhabitable means you CAN live there, not that you CAN'T. Habitable isn't actually a word.
The word meaning you can't live in a place is UNinhabitable. Sorry for bothering you, but I just thought you should know.

**Comment by Nimbleguy** [comment]
Wow, I'm surprised people still use this, to be honest. It's been fixed (assuming you mean in the project description), thanks for telling me.
